/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import diu.swe.habib.JPanelSlider.JPanelSlider;
import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.ResultSet;
import com.mysql.jdbc.Statement;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import java.sql.SQLException;
import javax.swing.JComboBox;
import javax.swing.JRadioButton;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import Koneksi.Koneksi;
import java.sql.PreparedStatement;
import javax.swing.ButtonGroup;
import javax.swing.RowFilter;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

public class HalUtamaAdmin extends javax.swing.JFrame {

        DefaultTableModel tma = new DefaultTableModel();
        ButtonGroup bg = new ButtonGroup();
       Connection conn= Koneksi.connection();
      // UPDATE `kepegawaian`.`tbldatauser` SET `password` = 'pega' WHERE `tbldatauser`.`idUser` = '4545'
       String update ="UPDATE tbldatauser SET NIP=?, password=?, type=?, status=? WHERE idUser=?";
    public HalUtamaAdmin() {
        initComponents();
        DataAdmin();

    }

    private void DataAdmin() {
        DefaultTableModel tma = new DefaultTableModel();
        tma.addColumn("ID USER");
        tma.addColumn("NIP");
        tma.addColumn("Password");
        tma.addColumn("Type");
        tma.addColumn("Status");
        jTableData.setModel(tma);
        try {
            Statement stm = (Statement) Koneksi.connection().createStatement();
            ResultSet rs = stm.executeQuery("select * from tbldatauser");
            while (rs.next()) {
                tma.addRow(new Object[]{
                    rs.getString("idUser"),
                    rs.getString("NIP"),
                    rs.getString("password"),
                    rs.getString("type"),
                    rs.getString("status"),});
                jTableData.setModel(tma);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Coba Lagi !!!");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanelSlider1 = new diu.swe.habib.JPanelSlider.JPanelSlider();
        panel1Akun = new usu.widget.glass.PanelGlass();
        jLabel2 = new javax.swing.JLabel();
        btnInsert = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        scrollPane1 = new java.awt.ScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableData = new javax.swing.JTable();
        ComboType = new javax.swing.JComboBox<String>();
        jRadioAktif = new javax.swing.JRadioButton();
        txtID = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        txtNIP = new javax.swing.JTextField();
        btncari = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        kehome = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Halaman Admin");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelSlider1.setBorder(null);
        jPanelSlider1.setOpaque(false);

        jLabel2.setText("Daftar Pengguna Sistem Informasi Kepegawaian");

        btnInsert.setText("Reset");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        btnSimpan.setText("Save");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel4.setText("ID User");

        jLabel5.setText("NIP");

        jLabel6.setText("Password");

        jLabel7.setText("Type");

        jLabel8.setText("Status");

        jTableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID User", "NIP", "Password", "Type", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableData);

        scrollPane1.add(jScrollPane2);

        ComboType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "Bagian Kepegawaian", "Rektor", "Pegawai" }));
        ComboType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboTypeActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioAktif);
        jRadioAktif.setText("Aktif");
        jRadioAktif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioAktifActionPerformed(evt);
            }
        });

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        txtNIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNIPActionPerformed(evt);
            }
        });

        btncari.setText("Search");
        btncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1AkunLayout = new javax.swing.GroupLayout(panel1Akun);
        panel1Akun.setLayout(panel1AkunLayout);
        panel1AkunLayout.setHorizontalGroup(
            panel1AkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1AkunLayout.createSequentialGroup()
                .addGroup(panel1AkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1AkunLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(panel1AkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addGap(22, 22, 22)
                        .addGroup(panel1AkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboType, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNIP, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioAktif, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel1AkunLayout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel2))
                    .addGroup(panel1AkunLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnInsert)
                        .addGap(34, 34, 34)
                        .addComponent(btnSimpan)
                        .addGap(29, 29, 29)
                        .addComponent(btnDelete)
                        .addGap(18, 18, 18)
                        .addComponent(btncari)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate)))
                .addContainerGap(155, Short.MAX_VALUE))
            .addComponent(scrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel1AkunLayout.setVerticalGroup(
            panel1AkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1AkunLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addGroup(panel1AkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(panel1AkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(panel1AkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(panel1AkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(ComboType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(panel1AkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioAktif)
                    .addComponent(jLabel8))
                .addGap(10, 10, 10)
                .addGroup(panel1AkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnInsert)
                    .addComponent(btnDelete)
                    .addComponent(btncari)
                    .addComponent(btnUpdate))
                .addGap(38, 38, 38)
                .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelSlider1.add(panel1Akun, "card2");

        getContentPane().add(jPanelSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 590, 390));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/picBack.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 500));

        jMenu1.setText("Akun");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        kehome.setText("Logout");
        kehome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kehomeMouseClicked(evt);
            }
        });
        jMenuBar1.add(kehome);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
   
//     jPanelSlider1.nextPanel(8, panel1Akun, jPanelSlider1.right);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void kehomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kehomeMouseClicked
        Home home = new Home();
        home.setLayout(new BorderLayout());
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_kehomeMouseClicked

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
      
        txtID.setText("");
        txtNIP.setText("");
        txtPassword.setText("");
        ComboType.setSelectedItem("");
        if (jRadioAktif.isSelected()) {
            JOptionPane.showMessageDialog(rootPane, "Aktif");
        } else {

        };

        // TODO add your handling code here:
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        btnSimpan();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void jTableDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDataMouseClicked
       tampil();
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableDataMouseClicked

    private void ComboTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboTypeActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_ComboTypeActionPerformed

    private void jRadioAktifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioAktifActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioAktifActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtNIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNIPActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
      delete();

        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btncariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariActionPerformed
        cari();
    }//GEN-LAST:event_btncariActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
    
        update();
        DataAdmin();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HalUtamaAdmin().setVisible(true);
            }
        });
    }

 public void update() {
        PreparedStatement stm = null;
        int view = jTableData.getSelectedRow();
        try{
            stm = conn.prepareCall(update);
            stm.setString(5, txtID.getText());
            stm.setString(1, txtNIP.getText());
            stm.setString(2, txtPassword.getText());
            System.out.println(String.valueOf(ComboType.getSelectedIndex()));
            switch (ComboType.getSelectedIndex()){
                case 0:
                    stm.setString(3, "Admin");
                    break;
                case 1:
                    stm.setString(3, "Bagian Kepegawaian");
                    break;
                case 2:
                    stm.setString(3, "Rektor");
                    break;
                case 3:
                    stm.setString(3, "Pegawai");
                    System.out.println("memilih combo pegawai");
                    break;
             }   
            
            if (jRadioAktif.isSelected()) {
            stm.setString(4, "Aktif");
            }else  {
                    JOptionPane.showMessageDialog(rootPane, "Pegawai terdaftar telah memiliki akun");
                
            }stm.executeUpdate();
               System.out.println("--------");
         }catch (SQLException e) {
            System.out.println(e);
            System.out.println(txtID.getText());
            System.out.println(txtNIP.getText());
            System.out.println(txtPassword.getText());
            System.out.println(String.valueOf(ComboType.getSelectedIndex()));
            System.out.println(String.valueOf(jRadioAktif.isSelected()));
//            System.out.println(String.valueOf(jRadioTdk.isSelected()));
         }
   
 }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboType;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btncari;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private diu.swe.habib.JPanelSlider.JPanelSlider jPanelSlider1;
    private javax.swing.JRadioButton jRadioAktif;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableData;
    private javax.swing.JMenu kehome;
    private usu.widget.glass.PanelGlass panel1Akun;
    private java.awt.ScrollPane scrollPane1;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNIP;
    private javax.swing.JTextField txtPassword;
    // End of variables declaration//GEN-END:variables

    @SuppressWarnings("empty-statement")
    private void tampil() {
      
        DefaultTableModel model =(DefaultTableModel) jTableData.getModel();
        txtID.setText(model.getValueAt(jTableData.getSelectedRow(), 0).toString());
        txtNIP.setText(model.getValueAt(jTableData.getSelectedRow(), 1).toString());
        txtPassword.setText(model.getValueAt(jTableData.getSelectedRow(), 2).toString());
        ComboType.setSelectedItem(model.getValueAt(jTableData.getSelectedRow(), 3).toString());
        if(model.getValueAt(jTableData.getSelectedRow(), 4).toString().equalsIgnoreCase("Aktif")){
            jRadioAktif.setSelected(true);
           
        }else{
                JOptionPane.showMessageDialog(rootPane,"Coba Lagi");
        }
        
    }  

    private void cari() {
    try {
            Statement stm = (Statement) Koneksi.connection().createStatement();
            ResultSet rs = stm.executeQuery("select * from tbldatauser where "
                    + "NIP='" + txtNIP.getText() + "'and type='"+ComboType.getSelectedItem()+"'");
            DefaultTableModel tba = new DefaultTableModel();
            tba.addColumn("ID USER");
            tba.addColumn("NIP");
            tba.addColumn("Password");
            jTableData.setModel(tba);

            while (rs.next()) {
                tba.addRow(new Object[]{
                    rs.getString("idUser"),
                    rs.getString("NIP"),
                    rs.getString("password"),
                    rs.getString("type")
                });
                jTableData.setModel(tba);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Salah");
        }    
    }

    private void btnSimpan() {
        String idUser = txtID.getText();
        String NIP = txtNIP.getText();
        String password = txtPassword.getText();
        String type = (String) ComboType.getSelectedItem();
        String status = null;
        if (jRadioAktif.isSelected()) {
            status = "Aktif";
        } else  {
            status = "Aktif";
        }
        try {
            Statement stm = (Statement) Koneksi.connection().createStatement();
            stm.executeUpdate("insert into tbldatauser VALUES ('" + idUser + "','" + NIP + "','" + password + "','" + type + "','" + status + "');");
            stm.close();
            JOptionPane.showMessageDialog(null, "Data Tersimpan");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data gagal simpan");
        }
        DataAdmin();
    
    }

    private void delete() {
          String idUser = txtID.getText();
        try {
            Statement stm = (Statement) Koneksi.connection().createStatement();
            stm.executeUpdate("DELETE from tbldatauser where idUser=('" + idUser + "');");
            JOptionPane.showMessageDialog(null, "Data Terhapus");
            txtID.setText("");
            txtNIP.setText("");
            txtPassword.setText("");
            ComboType.setSelectedItem("");
            String status = null;
            txtID.requestFocus();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data gagal tambah");
        }
        DataAdmin();
    }
    
    public void cariType(String query){
        TableRowSorter<DefaultTableModel> ta = new TableRowSorter<DefaultTableModel>(tma);
        jTableData.setRowSorter(ta);
        //cek filternya
        if(query != "None"){
            ta.setRowFilter(RowFilter.regexFilter(query));
        }else{
            jTableData.setRowSorter(ta);
        }
    }
//    public void radiogroup(){
//        bg.add(jRadioAktif);
//        bg.add(jRadioTdk); 
//    }
}

    
       
             
        
    


