/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.BorderLayout;
import Koneksi.Koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Girah Ihtama
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    private static String UserName;
    public Home() {
        initComponents();
    }
    
    public JTextField gettxtUsernameHome(){
        return lblUserName;
    }
    public static String getUserName(){
//        System.out.println("getUserName:"+lblUserName.getText());
        return UserName;    
    }
    
    public void setUserName(String username){
        this.UserName = lblUserName.getText();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGlass1 = new usu.widget.glass.PanelGlass();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblUserName = new javax.swing.JTextField();
        btnLogin1 = new javax.swing.JButton();
        lblnotifikasi = new javax.swing.JLabel();
        showpassword = new javax.swing.JCheckBox();
        lblPassword = new javax.swing.JPasswordField();
        label1 = new usu.widget.Label();
        label2 = new usu.widget.Label();
        type = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistem Informasi Kepegawaian");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelGlass1.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/resources/picHome.jpg"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel7.setText("SISTEM INFORMASI");

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel8.setText("KEPEGAWAIAN");

        jLabel9.setText("Username");

        jLabel10.setText("Password");

        jLabel11.setText(" : ");

        jLabel12.setText(" : ");

        lblUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblUserNameActionPerformed(evt);
            }
        });

        btnLogin1.setText("Login");
        btnLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogin1ActionPerformed(evt);
            }
        });

        lblnotifikasi.setFont(new java.awt.Font("Harrington", 1, 18)); // NOI18N
        lblnotifikasi.setForeground(new java.awt.Color(255, 51, 0));
        lblnotifikasi.setText("Selamat Datang di Sistem Informasi Kepegawaian");

        showpassword.setText("Show Password");
        showpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpasswordActionPerformed(evt);
            }
        });

        label1.setText("Type");

        label2.setText(":");

        type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "Pegawai", "Bagian Kepegawaian", "Rektor" }));
        type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGlass1Layout = new javax.swing.GroupLayout(panelGlass1);
        panelGlass1.setLayout(panelGlass1Layout);
        panelGlass1Layout.setHorizontalGroup(
            panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass1Layout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addGroup(panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass1Layout.createSequentialGroup()
                        .addComponent(lblnotifikasi)
                        .addGap(123, 123, 123))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass1Layout.createSequentialGroup()
                        .addGroup(panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnLogin1, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                            .addGroup(panelGlass1Layout.createSequentialGroup()
                                .addGroup(panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(panelGlass1Layout.createSequentialGroup()
                                            .addComponent(jLabel10)
                                            .addGap(20, 20, 20)
                                            .addComponent(jLabel12))
                                        .addGroup(panelGlass1Layout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel11)))
                                    .addGroup(panelGlass1Layout.createSequentialGroup()
                                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(42, 42, 42)
                                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblUserName)
                                    .addGroup(panelGlass1Layout.createSequentialGroup()
                                        .addComponent(lblPassword)
                                        .addGap(18, 18, 18)
                                        .addComponent(showpassword))
                                    .addComponent(type, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(148, 148, 148))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(182, 182, 182))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(214, 214, 214))))
        );
        panelGlass1Layout.setVerticalGroup(
            panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(23, 23, 23)
                .addGroup(panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(showpassword)
                    .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(btnLogin1)
                .addGap(18, 18, 18)
                .addComponent(lblnotifikasi, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        getContentPane().add(panelGlass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, 3, 690, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblUserNameActionPerformed

    private void btnLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogin1ActionPerformed
        System.out.println("btnLogin: "+lblUserName.getText());        
        UserName = lblUserName.getText();
        System.out.println("getUserName ning njero: " + getUserName());
        String login = (String)type.getSelectedItem();
        System.out.println("login:"+login);
        Connection con;
        con = Koneksi.connection();
        try{
            
            final String sql = "select NIP, password, type from tbldatauser where NIP = ? and password = ? and type = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, lblUserName.getText());
            pst.setString(2, String.valueOf(lblPassword.getPassword()));
            pst.setString(3, (String) type.getSelectedItem());
            ResultSet result = pst.executeQuery();
            
            if(result.next()){
                //System.out.println(Arrays.toString(sql.getBytes()));
                System.out.println("login:"+login);
                if(login.equalsIgnoreCase("Admin")){
                HalUtamaAdmin admin = new HalUtamaAdmin();
                admin.setLayout(new BorderLayout());
                admin.setVisible(true);
                dispose();
                this.setVisible(false);
                }else if (login.equalsIgnoreCase("Bagian Kepegawaian")) {
                    HalUtamaBK bk = new HalUtamaBK();
                    bk.setLayout(new BorderLayout());
                    bk.setVisible(true);
                    dispose();
//                    this.setVisible(false);
                }else if (login.equalsIgnoreCase("Rektor")) {
                    HalUtamaRektor framerektor = new HalUtamaRektor();
                    framerektor.setLayout(new BorderLayout());
                    framerektor.setVisible(true);
                    dispose();
                    this.setVisible(false);
                }else if (login.equalsIgnoreCase("Pegawai")) {
                    HalUtamaPegawai framepegawai = new HalUtamaPegawai();
                    framepegawai .setLayout(new BorderLayout());
                    framepegawai.setVisible(true);
                    dispose();
//                    this.setVisible(false);
                } else {
                    lblnotifikasi.setText("Username atau password salahs");
                }
            }
        }catch (SQLException e){
            JOptionPane.showMessageDialog(this, " "+e.getMessage(), "INFORMATION", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_btnLogin1ActionPerformed

    private void showpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpasswordActionPerformed
        if (showpassword.isSelected()){
            lblPassword.setEchoChar((char)0);
        } else {
            lblPassword.setEchoChar((char)'*');
        }
    }//GEN-LAST:event_showpasswordActionPerformed

    private void typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private usu.widget.Label label1;
    private usu.widget.Label label2;
    private javax.swing.JPasswordField lblPassword;
    private javax.swing.JTextField lblUserName;
    private javax.swing.JLabel lblnotifikasi;
    private usu.widget.glass.PanelGlass panelGlass1;
    private javax.swing.JCheckBox showpassword;
    private javax.swing.JComboBox type;
    // End of variables declaration//GEN-END:variables
}
