/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PengajuPensiun;

import PengajuPangkat.*;
import javax.swing.*;

public class BK_PengajuPensiun extends javax.swing.JPanel {

    /**
     * Creates new form PengajuPangkatBK
     */
    BK_ControllerPengPens bcp;

    public BK_PengajuPensiun() {
        initComponents();
        //bcp = new BK_ControllerPengPens(this);
        bcp.isiTable();
     
        
    }

    public JTable getTblPengPensBk() {
        return tblPengPensBk;
    }

    public JTextField getTxtIdPengPensiBK() {
        return txtIdPengPensiBK;
    }

    public JTextField getTxtStatPengPensBk() {
        return txtStatPengPensBk;
    }

    public JTextField getTxtnipPengPensBk() {
        return txtnipPengPensBk;
    }

    public JButton getBtnpensBK() {
        return btnpensBK;
    }
    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel200 = new javax.swing.JLabel();
        jLabel182 = new javax.swing.JLabel();
        jLabel183 = new javax.swing.JLabel();
        jLabel203 = new javax.swing.JLabel();
        txtIdPengPensiBK = new javax.swing.JTextField();
        txtnipPengPensBk = new javax.swing.JTextField();
        txtStatPengPensBk = new javax.swing.JTextField();
        btnpensBK = new javax.swing.JButton();
        jScrollPane11 = new javax.swing.JScrollPane();
        tblPengPensBk = new javax.swing.JTable();

        jLabel200.setText("Daftar Pegawai Pengaju Pensiun");

        jLabel182.setText("ID");

        jLabel183.setText("NIP");

        jLabel203.setText("Status");

        txtStatPengPensBk.setText("TUNGGU");

        btnpensBK.setText("Tunggu Prsetujuan");
        btnpensBK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpensBKActionPerformed(evt);
            }
        });

        tblPengPensBk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "NIP", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblPengPensBk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPengPensBkMouseClicked(evt);
            }
        });
        jScrollPane11.setViewportView(tblPengPensBk);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(jLabel200))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnpensBK)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel182, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel183, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel203, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(76, 76, 76)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtIdPengPensiBK)
                                    .addComponent(txtnipPengPensBk)
                                    .addComponent(txtStatPengPensBk, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel200)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel182)
                    .addComponent(txtIdPengPensiBK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel183)
                    .addComponent(txtnipPengPensBk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel203)
                    .addComponent(txtStatPengPensBk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnpensBK)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnpensBKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpensBKActionPerformed

        bcp.insert();
bcp.isiTable();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnpensBKActionPerformed

    private void tblPengPensBkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPengPensBkMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_tblPengPensBkMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnpensBK;
    private javax.swing.JLabel jLabel182;
    private javax.swing.JLabel jLabel183;
    private javax.swing.JLabel jLabel200;
    private javax.swing.JLabel jLabel203;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JTable tblPengPensBk;
    private javax.swing.JTextField txtIdPengPensiBK;
    private javax.swing.JTextField txtStatPengPensBk;
    private javax.swing.JTextField txtnipPengPensBk;
    // End of variables declaration//GEN-END:variables
}
